/**
 * @description       : 
 * @author            : Mohammed Mahimood
 * @group             : 
 * @last modified on  : 06-16-2026
 * @last modified by  : Mohammed Mahimood
**/
public with sharing class NewTestingVsCode {

     public static void methodDummy(String message){
    String name='Mahimood';
    String newd='my';
    System.debug('Replay Debugger Test');
    System.debug(message+' '+name);
    //NewTestingVsCode.methodDummy('zzzzzzzzzzzzzzzzzzzzzzzzz');
    for(Integer i=0;i<20;i++){
      System.debug(i);
    }
  
 }
}