// Calling the STATIC method directly using the Class Name
/*
Decimal currentTax = DiscountControllerMethods.getTaxRate();
System.debug('Static Method Output (Tax): ' + currentTax);
*/
// Calling the INSTANCE method by instantiating the class first
DiscountControllerMethods controllerInstance = new DiscountControllerMethods();
//Decimal finalTotal = controllerInstance.calculateFinalPrice(100.00);
//System.debug('Instance Method Output (Total): ' +controllerInstance.name );
LeadRatingController('Mahimood',08);
System.debug(controllerInstance.leadStatus+'  '+controllerInstance.leadScore );
